(function () {
    'use strict';

    angular.module('app.needs', []).config(config);

    config.$inject = ['$translateProvider'];

    function config($translateProvider) {
        $translateProvider.translations('ua', {
            needs: {
                lookingFor: 'Що ви шукаєте',
                needsTitle: 'Потреби',
                author: 'Автор',
                category: 'Категорія',
                edit: 'Редагувати',
                display: 'Відображати',
                firstPage: 'Перша',
                lastPage: 'Остання',
                previousPage: 'Попередня',
                nextPage: 'Наступна',

                needsPaginationLabel: 'потреб',
                allNeeds: 'Усі потреби',
                needsFound: 'За Вашим запитом знайдено потреб: {{count}}',
                nothingFound: 'На жаль за Вашим запитом нічого не знайдено.',

                need: 'Потреба',
                published: 'Опубліковано',
                needDescription: 'Опис потреби',
                description: 'Опис',
                actuality: 'Актуальність',
                address: 'Адреса',
                convenientTime: 'Зручний час',
                canTake: 'Зможу забрати',
                close: 'Закрити',
                delete: 'Видалити',
                respond: 'Відгукнутись',
                cancelResponse: 'Відмінити відгук',
                details: 'Деталі',
                typeDetailsPlaceholder: 'Введіть будь ласка деталі',
                submit: 'Підтвердити',
                userName: 'Ім\'я користувача',
                phoneNumber: 'Телефон',
                receive: 'Отримати',
                confirmAssistance: 'Підтвердити отримання допомоги',
                cancelAssistanceFromUser: 'Відмовитися від допомоги цього користувача',
                needIsClosed: 'Ця потреба закрита',
                deleteNeed: 'Ви справді хочете видалити дану потребу?',
                editingOfNeed: 'Редагування потреби',
                needName: 'Назва',
                selectRegion: 'Виберіть область',
                selectCity: 'Виберіть місто',
                save: 'Зберегти',
                cancel: 'Відмінити',
                requiredField: 'Обов\'язкове поле',
                newNeed: 'Нова потреба',
                name: 'Назва',
                nameOfNeedPlaceholder: 'Назва потреби',
                selectCategoryPlaceholder: 'Виберіть категорію',
                newNeedDescription: 'Опис потреби',
                describeNeedPlaceholder: 'Опишіть вашу потребу',
                photo: 'Фото',
                dateTimePlaceholder: 'Пн-Пт, 10:00 - 19:00;',
                yesRButton: 'Так',
                noRButton: 'Ні',
                publishButton: 'Опублікувати',
                backButton: 'Назад',
                furtherButton: 'Далі',
                selectImageButton: 'Вибрати зображення',
                uploadButton: 'Завантажити',
                newProjectTitle: 'Новий проект',
                textPlaceholder: 'Благодійна акція на день святого Миколая',
                projectDescription: 'Опис проекту',
                describeProjectPlaceholder: 'Опишіть ваш проект'
            }
        });
        $translateProvider.translations('ru', {
            needs: {
                lookingFor: 'Что вы ищете',
                needsTitle: 'Потребности',
                author: 'Автор',
                category: 'Категория',
                edit: 'Редактировать',
                display: 'Отображать',
                firstPage: 'Первая',
                lastPage: 'Последняя',
                previousPage: 'Предыдущая',
                nextPage: 'Следующая',

                needsPaginationLabel: 'потребностей',
                allNeeds: 'Все потребности',
                needsFound: 'По Вашему запросу найдено потребностей: {{count}}',
                nothingFound: 'К сожалению по вашему запросу ничего не найдено.',
                need: 'Потребность',
                published: 'Опубликовано',
                description: 'Описание',
                actuality: 'Актуальность',
                canTake: 'Смогу забрать',
                close: 'Закрыть',
                delete: 'Удалить',
                respond: 'Откликнуться',
                cancelResponse: 'Отменить отзыв',
                details: 'Детали',
                typeDetailsPlaceholder: 'Введите пожалуйста детали',
                submit: 'Подтвердить',
                userName: 'Имя пользователя',
                phoneNumber: 'Телефон',
                receive: 'Получить',
                confirmAssistance: 'Подтвердить получение помощи',
                cancelAssistanceFromUser: 'Отказаться от помощи этого пользователя',
                needIsClosed: 'Эта потребность закрыта',
                deleteNeed: 'Вы действительно хотите удалить данную потребность?',
                editingOfNeed: 'Редактирование потребности',
                needName: 'Название',
                needDescription: 'Описание потребности',
                photo: 'Фото',
                selectRegion: 'Выберите область',
                selectCity: 'Выберите город',
                address: 'Адрес',
                convenientTime: 'Удобное время',
                save: 'Сохранить',
                cancel: 'Отменить',
                requiredField:'Обязательное поле',
                newNeed: 'Новая потребность',
                name: 'Название',
                nameOfNeedPlaceholder: 'Название потребности',
                selectCategoryPlaceholder: 'Выберите категорию',
                newNeedDescription: 'Описание потребности',
                describeNeedPlaceholder: 'Опишите вашу потребность',
                dateTimePlaceholder: 'Пн-Пт, 10:00 - 19:00;',
                yesRButton: 'Да',
                noRButton: 'Нет',
                publishButton: 'Опубликовать',
                backButton: 'Назад',
                furtherButton: 'Далее',
                selectImageButton: 'Выбрать изображение',
                uploadButton: 'Загрузить',
                newProjectTitle: 'Новый проект',
                textPlaceholder: 'Благотворительная акция в день святого Николая',
                projectDescription: 'Описание проекта',
                describeProjectPlaceholder: 'Опишите ваш проект'
            }
        });
    }
})();
